"""Stored column names that are no longer the names the code uses.

A full ledger rebuild replays every snapshot in consolidated/ back to
2025-04, so the code must keep reading headers written by every earlier
version of itself. Those files are the record of what was published on each
day and are never rewritten - the translation happens on read instead.

Keyed by file, not global. `Verified Date` means the date a human recorded a
verdict in dropped_award_status.csv and the date automation last changed one
in auto_verification.csv; a single flat table could not hold both, which is
why `utils.read_rows` resolves the table from the path rather than taking one
map for every file.

Each table maps a stored name to the current one. Two rules make them safe to
apply to a file that has already been migrated, both asserted in
tests/test_csv_aliases.py:

  - no current name may also be a stored name, or a second pass would rename
    it again;
  - no two stored names may map to the same current name, or reading would
    silently merge two columns.
"""

import os

# consolidated/nasa_contract_cancellations_<date>.csv and its predecessors.
# Three header generations exist across the 400-odd archived files; the only
# column ever removed is Latest Modification Date, which is ignored on read.
SNAPSHOT = {
    "Recipient": "Recipient Name",
    "District": "Recipient Congressional District",
    "Business Categories": "Recipient Business Categories",
    "URL": "USAspending URL",
    # award_amount is total_obligation - an obligation, not the contract
    # ceiling USAspending's glossary calls "Current Award Amount".
    "Award Amount": "Current Obligated Amount",
    # period_of_performance_current_end_date, whose own help text reads "The
    # current, not original, period of performance end date".
    "End Date": "Current End Date",
    # Usually the terminating transaction's text, not the award's blurb.
    "Description": "Award or Action Description",
    "Detection": "Detection Evidence",
    # Every claim is DOGE's assertion, not an observation this tracker made.
    "Claiming Source": "Claimed By",
    "Claimed Status": "DOGE Claimed Status",
    "Claimed Savings": "DOGE Claimed Savings",
    "Claim Date": "DOGE Claim Date",
}

# consolidated/master_ledger.csv. Everything a snapshot carries, plus the
# columns only the ledger has. Regenerated by a full rebuild, so it needs
# translating on the incremental path and by its other readers.
LEDGER = {
    **SNAPSHOT,
    "Sources": "Flagged By",
    "First Seen": "First Flagged Date",
    "Last Seen": "Last Flagged Date",
    "Status": "Tracking Status",
    "Status Detail": "Tracking Status Detail",
    "Claim Revisions": "DOGE Claim Revisions",
    "Claim Divergence": "DOGE Claim vs Outcome",
    "First Award Amount": "Obligated Amount When First Flagged",
    "First End Date": "End Date When First Flagged",
    # The running maximum of cumulative federal_action_obligation.
    "Transaction Baseline Amount": "Peak Cumulative Obligation",
    "Auto Status": "Automated Verdict",
    # Marks when the verdict last *changed*, not when the award was checked.
    "Auto Verified Date": "Automated Verdict Date",
}

# verification/dropped_award_status.csv - human-owned, never machine-written.
# Its Verified Date is a person's, and deliberately not renamed alongside
# auto_verification.csv's, which is the reason these tables are per-file.
HUMAN_VERDICTS = {
    "Status": "Tracking Status",
}

# verification/auto_verification.csv - reverify_awards.py's screening verdicts.
AUTO_VERDICTS = {
    "Auto Status": "Automated Verdict",
    "Verified Date": "Automated Verdict Date",
    "Transaction Baseline Amount": "Peak Cumulative Obligation",
}

# verification/initial_reported_end_dates.csv - write-once provenance.
INITIAL_END_DATES: dict[str, str] = {}

# verification/award_transaction_facts.csv - transaction-derived provenance.
TRANSACTION_FACTS: dict[str, str] = {}

# verification/award_period_change_facts.csv - mirror period-change facts.
PERIOD_CHANGE_FACTS: dict[str, str] = {}

LEDGER_BASENAME = "master_ledger.csv"
SNAPSHOT_DIR = "consolidated"

_BY_BASENAME = {
    LEDGER_BASENAME: LEDGER,
    "dropped_award_status.csv": HUMAN_VERDICTS,
    "auto_verification.csv": AUTO_VERDICTS,
    "initial_reported_end_dates.csv": INITIAL_END_DATES,
    "award_transaction_facts.csv": TRANSACTION_FACTS,
    "award_period_change_facts.csv": PERIOD_CHANGE_FACTS,
}

ALL_TABLES = (
    SNAPSHOT,
    LEDGER,
    HUMAN_VERDICTS,
    AUTO_VERDICTS,
    INITIAL_END_DATES,
    TRANSACTION_FACTS,
    PERIOD_CHANGE_FACTS,
)


def is_snapshot(path: str) -> bool:
    """Whether `path` is a daily snapshot rather than the ledger beside it.

    Matches what build_master_ledger.snapshot_files() replays: any CSV in
    consolidated/ except the ledger. Snapshot filenames have changed twice, so
    the directory is the reliable signal, not the name.
    """
    return (
        os.path.basename(os.path.dirname(os.path.abspath(path))) == SNAPSHOT_DIR
        and os.path.basename(path) != LEDGER_BASENAME
    )


def aliases_for(path: str) -> dict[str, str]:
    """The stored-name translation for `path`, empty if it needs none.

    Resolved from the path so that no caller has to know which table applies.
    Forgetting to pass one would not raise - an un-aliased read returns stored
    keys, `row.get()` returns None, and whatever was checking that value stops
    checking it.
    """
    table = _BY_BASENAME.get(os.path.basename(path))
    if table is not None:
        return table
    return SNAPSHOT if is_snapshot(path) else {}
