"""Stored column names that are no longer the names the code uses.

A full ledger rebuild replays every snapshot in consolidated/ back to
2025-04, so the code must keep reading headers written by every earlier
version of itself. Those files are the record of what was published on each
day and are never rewritten - the translation happens on read instead.

Keyed by file, not global. `Verified Date` means the date a human recorded a
verdict in dropped_award_status.csv and the date automation last changed one
in auto_verification.csv; a single flat table could not hold both, which is
why `utils.read_rows` resolves the table from the path rather than taking one
map for every file.

Each table maps a stored name to the current one. Two rules make them safe to
apply to a file that has already been migrated, both asserted in
tests/test_csv_aliases.py:

  - no current name may also be a stored name, or a second pass would rename
    it again;
  - no two stored names may map to the same current name, or reading would
    silently merge two columns.
"""

import os

# consolidated/nasa_contract_cancellations_<date>.csv and its predecessors.
# Three header generations exist across the 400-odd archived files; the only
# column ever removed is Latest Modification Date, which is ignored on read.
SNAPSHOT = {
    "Recipient": "Recipient Name",
    "District": "Recipient Congressional District",
    "Business Categories": "Recipient Business Categories",
    "URL": "USAspending URL",
    # award_amount is total_obligation - an obligation, not the contract
    # ceiling USAspending's glossary calls "Current Award Amount".
    "Award Amount": "Current Obligated Amount",
    # period_of_performance_current_end_date, whose own help text reads "The
    # current, not original, period of performance end date".
    "End Date": "Current End Date",
    # Usually the terminating transaction's text, not the award's blurb.
    "Description": "Award or Action Description",
    "Detection": "Detection Evidence",
    # Qualified once a second termination answer was published beside it - see
    # award_transaction_facts.terminating_index.
    "Termination Modification Number": "Action Code Termination Modification",
    "Termination Action Date": "Action Code Termination Date",
    # Every claim is DOGE's assertion, not an observation this tracker made.
    "Claiming Source": "Claimed By",
    "Claimed Status": "DOGE Claimed Status",
    "Claimed Savings": "DOGE Claimed Savings",
    "Claim Date": "DOGE Claim Date",
}

# consolidated/master_ledger.csv. Everything a snapshot carries, plus the
# columns only the ledger has. Regenerated by a full rebuild, so it needs
# translating on the incremental path and by its other readers.
LEDGER = {
    **SNAPSHOT,
    "Sources": "Flagged By",
    "First Seen": "First Flagged Date",
    "Last Seen": "Last Flagged Date",
    "Status": "Tracking Status",
    "Status Detail": "Tracking Status Detail",
    "Claim Revisions": "DOGE Claim Revisions",
    "Claim Divergence": "DOGE Claim vs Outcome",
    "First Award Amount": "Obligated Amount When First Flagged",
    "First End Date": "End Date When First Flagged",
    # The running maximum of cumulative federal_action_obligation.
    "Transaction Baseline Amount": "Peak Cumulative Obligation",
    "Auto Status": "Automated Verdict",
    # Marks when the verdict last *changed*, not when the award was checked.
    "Auto Verified Date": "Automated Verdict Date",
}

# verification/dropped_award_status.csv - human-owned, never machine-written,
# and migrated in place, so there is nothing left to translate.
#
# Empty on purpose rather than deleted: this file is the one a person types
# into, and an alias here would be pure cost. It would mean the header they see
# says one thing while all three readers subscript another, and it would
# permanently reserve the generic name "Status" - the table invariants forbid a
# stored name from ever becoming a current one. Its Verified Date stays a
# person's timestamp and is deliberately NOT renamed alongside
# auto_verification.csv's, which is why these tables are per-file at all.
HUMAN_VERDICTS: dict[str, str] = {}

# verification/auto_verification.csv - reverify_awards.py's screening verdicts.
# Migrated in place too, but kept: reverify_awards rewrites this file wholesale
# on every run, so a run from pre-migration code can still put the old header
# back until that version is gone.
AUTO_VERDICTS = {
    "Auto Status": "Automated Verdict",
    "Verified Date": "Automated Verdict Date",
    "Transaction Baseline Amount": "Peak Cumulative Obligation",
    # These two now reach the ledger, so they need names that say which of the
    # two termination rules produced them.
    "Termination Mod": "Verified Termination Modification",
    "Termination Date": "Verified Termination Date",
}

# verification/initial_reported_end_dates.csv - write-once provenance.
INITIAL_END_DATES: dict[str, str] = {}

# verification/award_transaction_facts.csv - transaction-derived provenance.
# search.py rewrites this file wholesale every day, so these two entries only
# have to survive one run of the current code; they are kept for the same
# reason as AUTO_VERDICTS', so an older checkout cannot strand the file.
TRANSACTION_FACTS = {
    "Termination Modification Number": "Action Code Termination Modification",
    "Termination Action Date": "Action Code Termination Date",
}

# verification/award_period_change_facts.csv - mirror period-change facts.
PERIOD_CHANGE_FACTS: dict[str, str] = {}

# Values, not headers. The source labels are written into the Source cell of
# every archived snapshot, and those files are never rewritten, so a rebuild
# replaying them has to translate the cell as well as the column.
#
# Only snapshots need this. The ledger's Flagged By is re-accumulated from
# these Source cells on every full rebuild, and its Tracking Status is
# recomputed outright, so both arrive already translated.
SNAPSHOT_VALUES = {
    "Source": {
        "NPDV": "NASA Procurement Data View",
        "NASAGrants": "NASA Grants",
        "LocalUSASpendingMirror": "Local USAspending Mirror",
        "USAspendingTerminations": "USAspending Terminations",
    }
}

LEDGER_BASENAME = "master_ledger.csv"
SNAPSHOT_DIR = "consolidated"

_BY_BASENAME = {
    LEDGER_BASENAME: LEDGER,
    "dropped_award_status.csv": HUMAN_VERDICTS,
    "auto_verification.csv": AUTO_VERDICTS,
    "initial_reported_end_dates.csv": INITIAL_END_DATES,
    "award_transaction_facts.csv": TRANSACTION_FACTS,
    "award_period_change_facts.csv": PERIOD_CHANGE_FACTS,
}

ALL_TABLES = (
    SNAPSHOT,
    LEDGER,
    HUMAN_VERDICTS,
    AUTO_VERDICTS,
    INITIAL_END_DATES,
    TRANSACTION_FACTS,
    PERIOD_CHANGE_FACTS,
)


def is_snapshot(path: str) -> bool:
    """Whether `path` is a daily snapshot rather than the ledger beside it.

    Matches what build_master_ledger.snapshot_files() replays: any CSV in
    consolidated/ except the ledger. Snapshot filenames have changed twice, so
    the directory is the reliable signal, not the name.
    """
    return (
        os.path.basename(os.path.dirname(os.path.abspath(path))) == SNAPSHOT_DIR
        and os.path.basename(path) != LEDGER_BASENAME
    )


def aliases_for(path: str) -> dict[str, str]:
    """The stored-name translation for `path`, empty if it needs none.

    Resolved from the path so that no caller has to know which table applies.
    Forgetting to pass one would not raise - an un-aliased read returns stored
    keys, `row.get()` returns None, and whatever was checking that value stops
    checking it.
    """
    table = _BY_BASENAME.get(os.path.basename(path))
    if table is not None:
        return table
    return SNAPSHOT if is_snapshot(path) else {}


def value_aliases_for(path: str) -> dict[str, dict[str, str]]:
    """Stored cell values for `path` that are no longer the current ones.

    Keyed by the column name *after* header translation, so the two passes
    compose in one order only: rename the columns, then map the cells.
    """
    return SNAPSHOT_VALUES if is_snapshot(path) else {}
