"""Stored column names that are no longer the names the code uses.

A full ledger rebuild replays every snapshot in consolidated/ back to
2025-04, so the code must keep reading headers written by every earlier
version of itself. Those files are the record of what was published on each
day and are never rewritten - the translation happens on read instead.

Keyed by file, not global. `Verified Date` means the date a human recorded a
verdict in dropped_award_status.csv and the date automation last changed one
in auto_verification.csv; a single flat table could not hold both, which is
why `utils.read_rows` resolves the table from the path rather than taking one
map for every file.

Each table maps a stored name to the current one. Two rules make them safe to
apply to a file that has already been migrated, both asserted in
tests/test_csv_aliases.py:

  - no current name may also be a stored name, or a second pass would rename
    it again;
  - no two stored names may map to the same current name, or reading would
    silently merge two columns.
"""

import os

# consolidated/nasa_contract_cancellations_<date>.csv and its predecessors.
# Three header generations exist across the 400-odd archived files; the only
# column ever removed is Latest Modification Date, which is ignored on read.
SNAPSHOT: dict[str, str] = {}

# consolidated/master_ledger.csv. Regenerated by a full rebuild, so it only
# needs translating on the incremental path and by its other readers.
LEDGER: dict[str, str] = {}

# verification/dropped_award_status.csv - human-owned, never machine-written.
HUMAN_VERDICTS: dict[str, str] = {}

# verification/auto_verification.csv - reverify_awards.py's screening verdicts.
AUTO_VERDICTS: dict[str, str] = {}

# verification/initial_reported_end_dates.csv - write-once provenance.
INITIAL_END_DATES: dict[str, str] = {}

# verification/award_transaction_facts.csv - transaction-derived provenance.
TRANSACTION_FACTS: dict[str, str] = {}

# verification/award_period_change_facts.csv - mirror period-change facts.
PERIOD_CHANGE_FACTS: dict[str, str] = {}

LEDGER_BASENAME = "master_ledger.csv"
SNAPSHOT_DIR = "consolidated"

_BY_BASENAME = {
    LEDGER_BASENAME: LEDGER,
    "dropped_award_status.csv": HUMAN_VERDICTS,
    "auto_verification.csv": AUTO_VERDICTS,
    "initial_reported_end_dates.csv": INITIAL_END_DATES,
    "award_transaction_facts.csv": TRANSACTION_FACTS,
    "award_period_change_facts.csv": PERIOD_CHANGE_FACTS,
}

ALL_TABLES = (
    SNAPSHOT,
    LEDGER,
    HUMAN_VERDICTS,
    AUTO_VERDICTS,
    INITIAL_END_DATES,
    TRANSACTION_FACTS,
    PERIOD_CHANGE_FACTS,
)


def is_snapshot(path: str) -> bool:
    """Whether `path` is a daily snapshot rather than the ledger beside it.

    Matches what build_master_ledger.snapshot_files() replays: any CSV in
    consolidated/ except the ledger. Snapshot filenames have changed twice, so
    the directory is the reliable signal, not the name.
    """
    return (
        os.path.basename(os.path.dirname(os.path.abspath(path))) == SNAPSHOT_DIR
        and os.path.basename(path) != LEDGER_BASENAME
    )


def aliases_for(path: str) -> dict[str, str]:
    """The stored-name translation for `path`, empty if it needs none.

    Resolved from the path so that no caller has to know which table applies.
    Forgetting to pass one would not raise - an un-aliased read returns stored
    keys, `row.get()` returns None, and whatever was checking that value stops
    checking it.
    """
    table = _BY_BASENAME.get(os.path.basename(path))
    if table is not None:
        return table
    return SNAPSHOT if is_snapshot(path) else {}
